/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BADVIBES;

import static BADVIBES.PARAMETROS.contResiduo;
import static BADVIBES.PARAMETROS.residuo;
import static BADVIBES.PROCESOS.Procesos;
import static BADVIBES.PROCESOS.contProcesos;
import static BADVIBES.Participante.i;
import static BADVIBES.Participante.participante;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YAEL
 */
public class Individual extends javax.swing.JFrame {

    /**
     * Creates new form Individual
     */
    public Individual() {
        initComponents();
    this.setIconImage(new ImageIcon(getClass().getResource("/source/procesos.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Residuo", "Cantidad", "Bonus"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 237, 550, 100));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 109, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha Final: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 109, 110, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Icon/101-taxes_15x15.png"))); // NOI18N
        jButton4.setText("Mostrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 147, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 109, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Inicial: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Matrícula:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, -1, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 71, 160, -1));

        jCheckBox7.setText("Alumno");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 20, 70, -1));

        jCheckBox8.setText("Servidor Público");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Clave S.Público:    ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 69, -1, 20));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 71, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 324, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XANAX/original_reciclaje_españoles.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Periodo", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Cantidad", "Bonus", "Estación"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 550, 100));
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Fecha Final: ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 110, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Icon/101-taxes_15x15.png"))); // NOI18N
        jButton6.setText("Mostrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Fecha Inicial: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 110, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Matrícula:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 92, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 92, 160, -1));

        jCheckBox9.setText("Alumno");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 49, 70, -1));

        jCheckBox10.setText("Servidor Público");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 49, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Clave S.Público:    ");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 20));
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Residuo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione residuo...", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 157, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 250, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XANAX/reciclaje-de-vidrio.jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -10, 910, 550));

        jTabbedPane1.addTab("Residuo", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        int filas = modelo.getRowCount();
        for (int m = 1; m <= filas; m++){
            modelo.removeRow(0);
        }
       // modelo.addRow(new Object[]{'1''2''3''4'});
    String varParticipante, varFechaInicial,varBandera, varFechafinal;
    int diaI, mesI, anioI, numI, diaF, mesF, anioF, numF;
    int diaA, mesA, anioA, numA;
    
    if (jCheckBox7.isSelected()){
        varParticipante = jTextField6.getText();
    }
    else {
        varParticipante = jTextField9.getText();
    }
    varFechaInicial = jTextField8.getText();
    varFechafinal = jTextField10.getText();
    String[]FechaI = varFechaInicial.split("/");
    diaI = Integer.parseInt(FechaI [0]);
    mesI = Integer.parseInt(FechaI [1]);
    anioI = Integer.parseInt(FechaI [2]);
    numI = (diaI*diaI) + (mesI*mesI) + (anioI*anioI);
            
    String[]FechaF = varFechaInicial.split("/");
    diaF = Integer.parseInt(FechaF [0]);
    mesF = Integer.parseInt(FechaF [1]);
    anioF = Integer.parseInt(FechaF [2]);
    numF = (diaF*diaF) + (mesF*mesF) + (anioF*anioF);
    //JOptionPane.showMessageDialog(null, "F1"+numI+"-"+numF,"Aviso",1);
    
    varBandera = "0";
    for(int m = 0; m < i; m++){
    if (varParticipante.equals(participante[m][1])){
        jTextField2.setText(participante[m][3] +" "+ participante[m][4] +" "+ participante[m][5]);
        varBandera = "1";
       }
    }
    if(varBandera.equals("0")){
        JOptionPane.showMessageDialog(null,"NO ENCONTRADO", "AVISO",0);
        
            }
    //CODIGO PARA INSERTAR LOS REGISTROS EN LA TABLA
    for(int m = 0; m < contProcesos; m++){
        
    String[] FechaA = Procesos[m][3].split("/");
    diaA = Integer.parseInt(FechaA[0]);
    mesA = Integer.parseInt(FechaA [1]);
    anioA = Integer.parseInt(FechaA[2]);
    numA = (diaA*diaA) + (mesA*mesA) + (anioA*anioA);
    
    if ((varParticipante.equals(Procesos[m][1]))&&
            (numA >= numI) && (numA <= numF)) {
        modelo.addRow(new Object[]{Procesos[m][3],Procesos[m][2],Procesos[m][6],Procesos[m][8]});
        }
        
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        jLabel16.setVisible(true);
        jLabel18.setVisible(false);          
        jTextField6.setVisible(true);
        jTextField9.setVisible(false);
        
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        jLabel16.setVisible(false);
        jLabel18.setVisible(true);          
        jTextField6.setVisible(false);
        jTextField9.setVisible(true);
  
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTable3.getModel();
        int filas = modelo.getRowCount();
        for(int m = 1; m <= filas; m++){
            modelo.removeRow(0);
        }
        //modelo.addRow(new Object[]{'1','2','3','4'});
        
        String varParticipante, varFechaInicial, varFechaFinal, varBandera, varResiduo = null;
        int diaI, mesI, anioI, numI, diaF, mesF, anioF, numF;
        int diaA, mesA, anioA, numA;
        //Código para convertir la fecha a entero y elevarlo al cuadrado
        if((jCheckBox9.isSelected())){
            varParticipante = jTextField7.getText();
        }
        else{
            varParticipante = jTextField13.getText();
            varResiduo = (String) jComboBox1.getSelectedItem();
        }
        varFechaInicial = jTextField12.getText();
        varFechaFinal = jTextField11.getText();
        varResiduo = (String) jComboBox1.getSelectedItem(); 
        
        String[] FechaI = varFechaInicial.split("/");
        diaI = Integer.parseInt(FechaI[0]);
        mesI = Integer.parseInt(FechaI[1]);
        anioI = Integer.parseInt(FechaI[2]);
        numI = (diaI*diaI) + (mesI*mesI) + (anioI*anioI);
        
        String[] FechaF = varFechaFinal.split("/");
        diaF = Integer.parseInt(FechaF[0]);
        mesF = Integer.parseInt(FechaF[1]);
        anioF = Integer.parseInt(FechaF[2]);
        numF = (diaF*diaF) + (mesF*mesF) + (anioF*anioF);
        //Código para buscar el nombre del participante
        varBandera = "0";
        for(int m = 0; m < i; m++){
            if(varParticipante.equals(participante[m][1])){
                jTextField1.setText(participante[m][3]+" "+participante[m][4]+" "+participante[m][5]);
                varBandera = "1";
            }
        }
        if(varBandera.equals("0")){
            JOptionPane.showMessageDialog(null, "NO encontro", "Aviso", 0);
        }
        //Código para insertar los registros en la tabla
         for(int m = 0; m < contProcesos; m++){
            String[] FechaA = Procesos[m][3].split("/");
            diaA = Integer.parseInt(FechaA[0]);
            mesA = Integer.parseInt(FechaA[1]);
            anioA = Integer.parseInt(FechaA[2]);
            numA = (diaA*diaA) + (mesA*mesA) + (anioA*anioA);            
             if((varParticipante.equals(Procesos[m][1])) && (numA >= numI) && (numA <= numF) && (varResiduo.equals(Procesos[m][2]))){
                 modelo.addRow(new Object[]{Procesos[m][3],Procesos[m][2],Procesos[m][6],Procesos[m][5]});
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
        jLabel21.setVisible(true);
        jLabel22.setVisible(false);    
        jTextField7.setVisible(true);
        jTextField13.setVisible(false);
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
        jLabel21.setVisible(false);
        jLabel22.setVisible(true);    
        jTextField7.setVisible(false);
        jTextField13.setVisible(true);
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Selecciona el residuo...");

        for(int x = 0;x < contResiduo;x++){
            if(!residuo[x][1].equals("")){
            jComboBox1.addItem(residuo[x][1]);
        }
      }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Individual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
