/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BADVIBES;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static BADVIBES.PARAMETROS.contResiduo;
import static BADVIBES.PARAMETROS.residuo;
import static BADVIBES.Participante.i;
import static BADVIBES.Participante.participante;

/**
 *
 * @author HP
 */
public class PROCESOS extends javax.swing.JFrame {

    public static int contProcesos = 0;
    public static String[][] Procesos = new String[1000][9];
    private Object jComboBox1;
    private Object jComboBox2;
    private Object jLabel5;
    private Object jTextField3;
    private Object jTextField2;
    private Object jLabel9;
    private Object jLabel6;
    private Object jLabel1;
    
    public static int year, mes, dia;
    Calendar fecha = new GregorianCalendar();
    

    /**
     * Creates new form PROCESOS
     */
    public PROCESOS() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/source/buscarp.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        txtMat = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField121 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jTextField21 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtMat3 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jComboBox27 = new javax.swing.JComboBox<>();
        jLabel115 = new javax.swing.JLabel();
        jTextField125 = new javax.swing.JTextField();
        jComboBox37 = new javax.swing.JComboBox<>();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jTextField45 = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        jComboBox40 = new javax.swing.JComboBox<>();
        jTextField47 = new javax.swing.JTextField();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jComboBox41 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROCESOS");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 270, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Nombre:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Icon/101-safe-box_15x15.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jCheckBox1.setText("Alumno");
        jCheckBox1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jCheckBox1ComponentShown(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jCheckBox2.setText("Servidor Público");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Estación: ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione residuo...", " " }));
        jComboBox4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox4FocusLost(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleecione estación...", "E1", "E2", "E3", "E4" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Residuo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Cantidad:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 150, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        jComboBox3.setEditable(true);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione división...", "D.Ingenieria Civil", "D.Quimica", "D.Informatica", "D.Contador Público", "D.Industrias Alimentarias" }));
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, -1));

        jComboBox5.setEditable(true);
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione área...", "Control escolar", "Intendencia", " " }));
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Matrícula:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("División: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Clave S. Publico:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Área:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, -1));
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 160, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XANAX/reciclaje-vidrio.jpg"))); // NOI18N
        jLabel20.setToolTipText("");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTabbedPane1.addTab("Altas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Estación: ");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione estación...", "E1", "E2", "E3", "E4" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 180, -1));

        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 220, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Nombre:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, -1));

        jCheckBox7.setText("Alumno");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 70, -1));

        jCheckBox8.setText("Servidor Público");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jComboBox7.setEditable(true);
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione residuo...", " ", " " }));
        jComboBox7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox7FocusLost(evt);
            }
        });
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Residuo: ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Cantidad");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 60, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Icon/101-pay-point_15x15.png"))); // NOI18N
        jButton5.setText("Borrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Fecha: ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 60, -1));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 140, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Icon/101-stats-6_15x15.png"))); // NOI18N
        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 160, -1));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 360));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Matrícula:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("División:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 20));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione division...", "D.Ingenieria Civil", "D.Quimica", "D.Informatica", "D.Contador Público", "D.Industrias Alimentarias" }));
        jPanel3.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 160, 20));

        txtMat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatFocusLost(evt);
            }
        });
        txtMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatActionPerformed(evt);
            }
        });
        jPanel3.add(txtMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Clave S.Público:    ");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Área:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 80, 20));

        jTextField121.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField121FocusLost(evt);
            }
        });
        jPanel3.add(jTextField121, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 150, 20));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione área...", "Control escolar", "Intendencia", " " }));
        jPanel3.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 150, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 610, 390));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setToolTipText("");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 340));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XANAX/reciclaje-vidrio.jpg"))); // NOI18N
        jLabel29.setToolTipText("");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        jTabbedPane1.addTab("Bajas", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Icon/101-stats-6_15x15.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 160, -1));
        jPanel4.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 768, -1, -1));

        jCheckBox11.setText("Alumno");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, -1));

        jCheckBox12.setText("Servidor Público");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 204, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Nombre:");
        jPanel4.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, -1));

        txtMat3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMat3FocusLost(evt);
            }
        });
        txtMat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMat3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtMat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, -1));

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setText("Matrícula:");
        jPanel4.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel85.setText("División:");
        jPanel4.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione division...", "D.Ingenieria Civil", "D.Quimica", "D.Informatica", "D.Contador Público", "D.Industrias Alimentarias" }));
        jPanel4.add(jComboBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 160, -1));

        jLabel115.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel115.setText("Clave S.Público:    ");
        jPanel4.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 20));

        jTextField125.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField125FocusLost(evt);
            }
        });
        jPanel4.add(jTextField125, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 131, -1));

        jComboBox37.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione área...", "Control escolar", "Intendencia", " " }));
        jComboBox37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox37ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 131, -1));

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel116.setText("Área:");
        jPanel4.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 80, 20));

        jLabel117.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel117.setText("Fecha: ");
        jPanel4.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 60, -1));
        jPanel4.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 140, -1));

        jLabel122.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel122.setText("Residuo: ");
        jPanel4.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jComboBox40.setEditable(true);
        jComboBox40.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione residuo...", " ", " " }));
        jPanel4.add(jComboBox40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 180, -1));

        jTextField47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField47ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 60, -1));

        jLabel123.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel123.setText("Cantidad");
        jPanel4.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel124.setText("Estación: ");
        jPanel4.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jComboBox41.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleecione estación...", "E1", "E2", "E3", "E4" }));
        jComboBox41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox41ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox41, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 142, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New Icon/101-investment-3_15x15.png"))); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XANAX/reciclaje-vidrio.jpg"))); // NOI18N
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        jTabbedPane1.addTab("Modificaciones", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String varResiduo, varParticipante; 
        String varEstacion, varFecha, varHora;
        
        
        double varCantidad, varBonus, varPorcentaje;
        
       
        if (jCheckBox1.isSelected()) {
           varParticipante = jTextField1.getText();
           
        } else {
          varParticipante = jTextField5.getText();  
          //jTextField4
        }
        varResiduo = (String) jComboBox4.getSelectedItem();
        varFecha = fecha.get(Calendar.DAY_OF_MONTH)+"/"+(fecha.get(Calendar.MONTH)+1)+"/"+ fecha.get(Calendar.YEAR);
        varHora = fecha.get(Calendar.HOUR)+":"+fecha.get(Calendar.MINUTE)+":"+fecha.get(Calendar.SECOND);
        varEstacion = (String) jComboBox9.getSelectedItem();
        varCantidad = Double.parseDouble(this.jTextField4.getText());
        
        varPorcentaje = 0;
        for(int h = 0; h <contResiduo; h++){
            if (varResiduo.equals(residuo[h][1])){
                varPorcentaje = Double.parseDouble(residuo[h][2]);       
            }
        }
        varBonus = varCantidad * varPorcentaje;
        if((varParticipante.equals("")) || (varResiduo.equals("")) || (varFecha.equals("")) || (varHora.equals("")) || 
                (varEstacion.equals("")) || (varCantidad <= 0) || (varBonus <= 0) || (varPorcentaje <= 0) ){
        JOptionPane.showMessageDialog(null,"Error: Faltan Datos", "Aviso", 0);
    }
        else{
            Procesos[contProcesos][0] = contProcesos +"";
            Procesos[contProcesos][1] = varParticipante;
            Procesos[contProcesos][2] = varResiduo;
            Procesos[contProcesos][3] = varFecha;
            Procesos[contProcesos][4] = varHora;
            Procesos[contProcesos][5] = varEstacion;
            Procesos[contProcesos][6] = varCantidad + "";
            Procesos[contProcesos][7] = varPorcentaje + "";
            Procesos[contProcesos][8] = varBonus + "";
            contProcesos++;
            JOptionPane.showMessageDialog(null,"Guardado, Bonus: " + varBonus, "Aviso", 0);  
        }
        for(int x = 0; x<= contProcesos; x++){
            for(int y = 0; y < 9; y++)
                System.out.print(Procesos[x][y] + " - ");
            System.out.println("");
        }
        
        
            
      

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        String[] division = {"Seleccione division...", "D. Civil", "D. Contador Publico",
            "D.Energias Renovables", "D. Informatica", "D. Industrias Alimentarias",
            "D. Quimica"};
        String[] area = {"Seleccione el area...", "Administracion", "Control escolar",
            "Directivo", "Intendencia", "Mantenimeinto"};
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(division));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(area));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(division));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(area));
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel15.setVisible(false);
        jTextField1.setVisible(false);
        jTextField5.setVisible(false);
        txtMat.setVisible(false);
        jTextField121.setVisible(false);
        jComboBox3.setVisible(false);
        jComboBox5.setVisible(false);
        jComboBox6.setVisible(false);
        jComboBox8.setVisible(false);

        jComboBox4.removeAllItems();
        jComboBox7.removeAllItems();
        jComboBox3.removeAllItems();
        jComboBox4.addItem("Selecciona el residuo...");
        jComboBox7.addItem("Selecciona el residuo...");
        jComboBox3.addItem("Selecciona división...");
        for (int x = 0; x < contResiduo; x++) {
            if (!residuo[x][1].equals("")) {
                jComboBox4.addItem(residuo[x][1]);
                jComboBox7.addItem(residuo[x][1]);
                jComboBox3.addItem(participante[x][2]);
            }
        }

    }//GEN-LAST:event_formComponentShown

    private void jCheckBox1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jCheckBox1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ComponentShown

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jLabel12.setVisible(false);
        jLabel15.setVisible(false);
        jTextField1.setVisible(true);
        jTextField5.setVisible(false);
        jComboBox3.setVisible(true);
        jComboBox5.setVisible(false);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(true);
        jLabel15.setVisible(true);
        jTextField1.setVisible(false);
        jTextField5.setVisible(true);
        jComboBox3.setVisible(false);
        jComboBox5.setVisible(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel15.setVisible(false);
        jTextField1.setVisible(false);
        jTextField5.setVisible(false);
        txtMat.setVisible(true);
        jTextField121.setVisible(false);
        jComboBox3.setVisible(false);
        jComboBox5.setVisible(false);
        jComboBox6.setVisible(true);
        jComboBox8.setVisible(false);
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(true);
        jLabel19.setVisible(true);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel15.setVisible(false);
        jTextField1.setVisible(false);
        jTextField5.setVisible(false);
        txtMat.setVisible(false);
        jTextField121.setVisible(true);
        jComboBox3.setVisible(false);
        jComboBox5.setVisible(false);
        jComboBox6.setVisible(false);
        jComboBox8.setVisible(true);
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked


    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown


    }//GEN-LAST:event_jPanel1ComponentShown

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   String varParticipante,varResiduo, varFecha, varBandera;
     if (jCheckBox7.isSelected()) {
           varParticipante = txtMat.getText();   
        } 
         else {
          varParticipante = jTextField121.getText();  
          
        }
        varResiduo =(String) jComboBox7.getSelectedItem();
        varFecha = jTextField8.getText();
        
    if  (varResiduo.equals("") || varFecha.equals("")  || varParticipante.equals("")){  
        
        JOptionPane.showMessageDialog(null, "Faltan parametros","Aviso", 0);
    } 
     else{
         varBandera = "0";
         for(int h = 0; h < contProcesos; h++){
             if (varParticipante.equals(Procesos[h][1])
                 && varResiduo.equals(Procesos[h][2])
                 && varFecha.equals(Procesos[h][3])){
                 for (int k = 0; k< i; k++){
                    if (varParticipante.equals(participante[k][1])){
                       jTextField10.setText(participante [k][3] + " " + participante [k][4] +" " + participante [k][5]);
                         if(jCheckBox7.isSelected()){ 
                            jComboBox6.setSelectedItem(participante[k][2]);
             }else {
            jComboBox8.setSelectedItem(participante[k][2]);
                         }
            jTextField7.setText(Procesos[h][6]);
            jComboBox10.setSelectedItem(participante[h][5]);
                         
                 }}
                     if(varBandera.equals("0")){
                         //JOptionPane.showMessageDialog(null,"No encontrado","Aviso", 0);
                     }          
                 }}}
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtMatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatFocusLost
        String varBuscar = "", varBandera;

        if (jCheckBox7.isSelected()) {
            varBuscar = txtMat.getText();
        }
        if (varBuscar.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese parámetros de búsqueda", "Aviso", 0);
        } else {
            varBandera = "0";
            for (int x = 0; x < i; x++) {
                if (varBuscar.equals(participante[x][1])) {
                    jTextField10.setText(participante[x][3] + " " + participante[x][4] + " " + participante[x][5]);
                    jComboBox6.setSelectedItem(participante[x][2]);
                    varBandera = "1";
                }
            }
            if (varBandera.equals("0")) {
                txtMat.setText("");
                jComboBox6.setSelectedItem("Seleccione division...");
                JOptionPane.showMessageDialog(null, "No se encuentra registro", "Aviso", 0);
            }
        }
    }//GEN-LAST:event_txtMatFocusLost

    private void txtMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatActionPerformed
        // TODO add your handling code here:\

    }//GEN-LAST:event_txtMatActionPerformed

    private void jTextField121FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField121FocusLost
         String varBuscar = "", varBandera;

        if (jCheckBox8.isSelected()) {
            varBuscar = jTextField121.getText();
        }
        if (varBuscar.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese parámetros de búsqueda", "Aviso", 0);
        } else {
            varBandera = "0";
            for (int x = 0; x < i; x++) {
                if (varBuscar.equals(participante[x][2])) {
                    jTextField10.setText(participante[x][3] + " " + participante[x][4] + " " + participante[x][5]);
                    jComboBox8.setSelectedItem(participante[x][1]);
                    varBandera = "1";
                }
            }
            if (varBandera.equals("0")) {
                jTextField121.setText("");
                jComboBox8.setSelectedItem("Seleccione área...");
                JOptionPane.showMessageDialog(null, "No se encuentra registro", "Aviso", 0);
            }
        }
    }//GEN-LAST:event_jTextField121FocusLost

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    String varParticipante,varResiduo, varFecha, varBandera;
     if (jCheckBox7.isSelected()) {
           varParticipante = txtMat.getText();   
        } 
         else {
          varParticipante = jTextField121.getText();  
          
        }
        varResiduo =(String) jComboBox7.getSelectedItem();
        varFecha = jTextField8.getText();
        
    if  (varResiduo.equals("") || varFecha.equals("")  || varParticipante.equals("")){  
        
        JOptionPane.showMessageDialog(null, "Faltan parametros","Aviso", 0);
    } 
 else{
         varBandera = "0";
         for(int h = 0; h < contProcesos; h++){
             if (varParticipante.equals(Procesos[h][1])
                 && varResiduo.equals(Procesos[h][2])
                 && varFecha.equals(Procesos[h][3])){
             Procesos[h][0] = "";
             Procesos[h][1] = "";
             Procesos[h][2] = "";
             Procesos[h][3] = ""; 
             Procesos[h][4] = "";
             Procesos[h][5] = "";
             Procesos[h][6] = "";
             Procesos[h][7] = "";
             Procesos[h][8] = "";
            jTextField10.setText("");
            jTextField7.setText("");
            jComboBox6.setSelectedItem("Seleccione division...");
            jComboBox8.setSelectedItem("Seleccione area...");
            jComboBox10.setSelectedItem("Seleccione estación...");
            varBandera = "1";
             }
         }
if (varBandera.equals("1")){
    JOptionPane.showMessageDialog(null, "Fue borrado","Aviso", 1);
} else
     {
       JOptionPane.showMessageDialog(null,"No borrado","Aviso", 0);  
     }
    }
                
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
        jLabel84.setVisible(true);
        jLabel85.setVisible(true);
        jLabel115.setVisible(false);
        jLabel10.setVisible(false);
        jLabel116.setVisible(false);
        txtMat3.setVisible(true);
        jTextField125.setVisible(false);
        jComboBox27.setVisible(true);
        jComboBox37.setVisible(false);
                                      
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
        jLabel84.setVisible(false);
        jLabel85.setVisible(false);
        jLabel115.setVisible(true);
        jLabel116.setVisible(true);
        jLabel10.setVisible(true);
        txtMat3.setVisible(false);
        jTextField125.setVisible(true);
        jComboBox27.setVisible(false);
        jComboBox37.setVisible(true);
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void txtMat3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMat3FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMat3FocusLost

    private void txtMat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMat3ActionPerformed

    private void jTextField125FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField125FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField125FocusLost

    private void jTextField47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField47ActionPerformed

    private void jComboBox41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox41ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String varParticipante,varResiduo, varFecha, varBandera;
     if (jCheckBox11.isSelected()) {
           varParticipante = txtMat3.getText();   
        } 
         else {
          varParticipante = jTextField125.getText();  
          
        }
        varResiduo =(String) jComboBox40.getSelectedItem();
        varFecha = jTextField45.getText();
        
    if  (varResiduo.equals("") || varFecha.equals("")  || varParticipante.equals("")){  
        
        JOptionPane.showMessageDialog(null, "Faltan parametros","Aviso", 0);
    } 
     else{
         varBandera = "0";
         for(int h = 0; h < contProcesos; h++){
             if (varParticipante.equals(Procesos[h][1])
                 && varResiduo.equals(Procesos[h][2])
                 && varFecha.equals(Procesos[h][3])){
                 for (int k = 0; k< i; k++)
                 {
                    if (varParticipante.equals(participante[k][1])){
                       jTextField21.setText(participante [k][3] + " " + participante [k][4] +" " + participante [k][5]);
                         if(jCheckBox11.isSelected()){ 
                            jComboBox27.setSelectedItem(participante[k][2]);
             }else {
            jComboBox37.setSelectedItem(participante[k][2]);
            jTextField47.setText(Procesos[h][6]);
            jComboBox41.setSelectedItem(participante[h][5]);
            varBandera = "1";
                         }
                 }
                     if(varBandera.equals("0")){
                         JOptionPane.showMessageDialog(null,"No encontrado","Aviso", 0);
                     }          
                 }}}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          String varParticipante,varResiduo, varFecha, varBandera;
          double varPorcentaje,varCantidad, varBonus;
          
     if (jCheckBox11.isSelected()) {
           varParticipante = txtMat.getText();   
        } 
         else {
          varParticipante = txtMat3.getText();  
          
        }
        varResiduo =(String) jComboBox40.getSelectedItem();
        varFecha = jTextField45.getText();
        
    if  (varResiduo.equals("") || varFecha.equals("")  || varParticipante.equals("")){  
        
        JOptionPane.showMessageDialog(null, "Faltan parametros","Aviso", 0);
    } 
 else{
         varBandera = "0";
         for(int h = 0; h < contProcesos; h++){
             if (varParticipante.equals(Procesos[h][1])
                 && varResiduo.equals(Procesos[h][2])
                 && varFecha.equals(Procesos[h][3])){
                 Procesos[h][5] = (String) jComboBox41.getSelectedItem();
                 Procesos[h][6] = jTextField47.getText();//cantidad
                 varCantidad = Double.parseDouble(this.jTextField47.getText());
                 for (int k = 0; k< contResiduo; k++){    
                    if (varResiduo.equals(residuo[k][1])){
                        varPorcentaje = Double.parseDouble(residuo[k][2]);
                        varBonus = varPorcentaje * varCantidad;
                         
             }
                {
                    Procesos[h][8] = "";
                    varBandera = "1";
                         }
                 }
                     if(varBandera.equals("0")){
                         JOptionPane.showMessageDialog(null,"No encontrado","Aviso", 0);
                     } 
                     else{
                         JOptionPane.showMessageDialog(null,"Modificado","Aviso", 1);
                 }
             
         }
         }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox37ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        String varBuscar = "", varBandera;

        if (jCheckBox1.isSelected()) {
            varBuscar = jTextField1.getText();
        }
        if (varBuscar.equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese parámetros de búsqueda", "Aviso", 0);
        } 
        else {
            varBandera = "0";
            for (int x = 0; x < i; x++) {
                if (varBuscar.equals(participante[x][1])) {
                    jTextField12.setText(participante[x][3] + " " + participante[x][4] + " " + participante[x][5]);
                    jComboBox3.setSelectedItem(participante[x][2]);
                    varBandera = "1";
                }
            }
            if (varBandera.equals("0")) {
                jTextField12.setText("");
                jComboBox3.setSelectedItem("Seleccione área...");
                JOptionPane.showMessageDialog(null, "No se encuentra registro", "Aviso", 0);
            }
        }
        
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10FocusLost

    private void jComboBox4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox4FocusLost
        // TODO add your handling code here:           
    }//GEN-LAST:event_jComboBox4FocusLost

    private void jComboBox7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox7FocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox7FocusLost

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < contResiduo; i++) {
            if (!residuo[i][1].equals("")) {
                jTextField7.setText(residuo[i][2]);
            }
    }
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROCESOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROCESOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROCESOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROCESOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PROCESOS().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox27;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox37;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox40;
    private javax.swing.JComboBox<String> jComboBox41;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField121;
    private javax.swing.JTextField jTextField125;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtMat3;
    // End of variables declaration//GEN-END:variables
}
